INSERT INTO PAYMENT_ENTITY
VALUES (1, '100');

INSERT INTO PAYMENT_ENTITY
VALUES (2, '200');

INSERT INTO PAYMENT_ENTITY
VALUES (3, '300');

INSERT INTO PAYMENT_ENTITY
VALUES (4, '400');

INSERT INTO CONTRACT_ENTITY
VALUES (1, 1, '001');

INSERT INTO CONTRACT_ENTITY
VALUES (2, 2, '002');

INSERT INTO CONTRACT_ENTITY
VALUES (3, 3, '003');

INSERT INTO CONTRACT_ENTITY
VALUES (4, 4, '004');